/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FineMainForm.java
 *
 * Created on May 13, 2011, 11:15:32 AM
 */
package aptech.view.attendace;

import api.AttendanceDAO;
import api.ClassOffer;
import api.ClassOfferDAO;
import api.FineObject;
import api.StudentDAO;
import api.StudentV2;
import aptech.util.AppUtil;
import aptech.util.Constant;
import aptech.view.control.CmbObject;
import aptech.view.control.FineTableModel;
import aptech.view.control.TtsCmbModel;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author bo
 */
public class FineMainForm extends javax.swing.JPanel {

    /** Creates new form FineMainForm */
    public FineMainForm() {
        initComponents();
        initClassCmbBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxClassName = new javax.swing.JComboBox();
        cbxStudent = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrlPn = new javax.swing.JScrollPane();
        lbMoney = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPercentAtt1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbStatus1 = new javax.swing.JLabel();

        jLabel1.setText("Class name");

        jLabel2.setText("Student name");

        cbxClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClassNameActionPerformed(evt);
            }
        });

        cbxStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStudentActionPerformed(evt);
            }
        });

        jLabel3.setText("Attendance Summary");

        jLabel4.setText("Fine levy");

        jLabel5.setText("Percent Of Attendace");

        jLabel6.setText("Egibility to get final Exam");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(cbxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(cbxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(scrlPn, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbPercentAtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cbxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cbxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel3))
                    .addComponent(scrlPn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPercentAtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClassNameActionPerformed
        resetLabelStatus();
        CmbObject selectedObj = (CmbObject) cbxClassName.getSelectedItem();
        if (selectedObj.getValue().equals("-1")) {
            cbxStudent.removeAllItems();
        } else {
            int classOfferId = Integer.valueOf(selectedObj.getValue());
            List<CmbObject> lstCmb = new ArrayList<CmbObject>();
            List<StudentV2> lstStudent = new StudentDAO().getAllStudentByClassOfferId(classOfferId);
            if (lstStudent.size() > 0) {
                for (StudentV2 studentObj : lstStudent) {
                    CmbObject cmbObj = new CmbObject(studentObj.getStudentCode() + "_" + studentObj.getName(), studentObj.getStudentId().toString());
                    lstCmb.add(cmbObj);
                }
                TtsCmbModel model = new TtsCmbModel(lstCmb);
                model.setFirstItemLabel("select student");
                cbxStudent.setModel(model);
                cbxStudent.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_cbxClassNameActionPerformed

    private void cbxStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStudentActionPerformed
        if (cbxStudent.getSelectedIndex() < 1) {
            return;
        }
        initGui();
        resetLabelStatus();
        CmbObject cmbObjClass = (CmbObject) cbxClassName.getSelectedItem();
        int classOfferId = Integer.valueOf(cmbObjClass.getValue());

        CmbObject cmbObjStudent = (CmbObject) cbxStudent.getSelectedItem();
        int studentId = Integer.valueOf(cmbObjStudent.getValue());
        List<FineObject> lstFine = new AttendanceDAO().generateFineLevy(classOfferId, studentId);
        tblModel = new FineTableModel();
        tblModel.setLstData(lstFine);
        tblFine.setModel(tblModel);
        calculateFine(lstFine);
        tblFine.revalidate();
        tblFine.repaint();

    }//GEN-LAST:event_cbxStudentActionPerformed
    private void resetLabelStatus() {
        this.lbPercentAtt1.setText("");
        this.lbMoney.setText("");
        this.lbStatus1.setText("");
        this.jLabel5.setVisible(false);
        this.jLabel6.setVisible(false);
        this.jLabel4.setVisible(false);

    }

    public void calculateFine(List<FineObject> lstFine) {
        NumberFormat format = new DecimalFormat("0.00");
        int totalLession = 0;
        int numberOfAtten = 0;
        for (FineObject fineObject : lstFine) {
            totalLession += fineObject.getNumberConduct();
            numberOfAtten += fineObject.getNumberOfAttendace();
        }
        if (totalLession > 0) {
            double percentOfAtt = ((double) numberOfAtten / (double) totalLession) ;
            this.lbPercentAtt1.setText(format.format(percentOfAtt*100) + "%");
            this.jLabel5.setVisible(true);
            this.jLabel6.setVisible(true);
            if (percentOfAtt < 0.7f) {
                this.lbStatus1.setText(Constant.NOT_EGILIBILITY_FINAL_EXAM);
                this.lbStatus1.setForeground(Color.red);
            } else if (percentOfAtt >= 0.7f && percentOfAtt <= 0.75) {
                this.lbStatus1.setText(Constant.MUSTPAY_EGILIBILITY_FINAL_EXAM);
                this.lbStatus1.setForeground(Color.PINK);
                int moneyMustPay = (totalLession - numberOfAtten) * 10;
                this.lbMoney.setText(moneyMustPay + "$");
                this.jLabel4.setVisible(true);
            } else {
                this.lbStatus1.setText(Constant.EGILIBILITY_FINAL_EXAM);
                this.lbStatus1.setForeground(Color.BLUE);
            }


        }

    }

    private void initClassCmbBox() {
        TtsCmbModel cmbModel = new TtsCmbModel();
        List<CmbObject> lstModel = new ArrayList<CmbObject>();
        List<ClassOffer> classTeachByStaffid = new ClassOfferDAO().getClassTeachByStaffid(AppUtil.UserToken.getStaffId());
        for (ClassOffer offer : classTeachByStaffid) {
            CmbObject cmb = new CmbObject(offer.getClassCode(), offer.getClassOfferId().toString());
            lstModel.add(cmb);
        }
        cmbModel.setLstData(lstModel);
        cmbModel.setFirstItemLabel("select your class");
        this.cbxClassName.setModel(cmbModel);
        cbxClassName.setSelectedIndex(0);

    }

    private void initGui() {
        tblFine = new JTable();
        scrlPn.setViewportView(tblFine);
        tblFine.setFillsViewportHeight(true);
        revalidate();
        repaint();
    }
    private JTable tblFine;
    private FineTableModel tblModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxClassName;
    private javax.swing.JComboBox cbxStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbMoney;
    private javax.swing.JLabel lbPercentAtt1;
    private javax.swing.JLabel lbStatus1;
    private javax.swing.JScrollPane scrlPn;
    // End of variables declaration//GEN-END:variables
}
