/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputStudent.java
 *
 * Created on Apr 2, 2011, 2:44:34 PM
 */
package aptech.view.student;

import api.Staff;
import api.StaffDAO;

/**
 *
 * @author bo
 */
public class InputStudent extends javax.swing.JPanel {

    /** Creates new form InputStudent */
    public InputStudent() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");
        add(jLabel1);

        jTextField1.setText("jTextField1");
        add(jTextField1);

        jButton1.setText("save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        StaffDAO dao = new StaffDAO();
        dao.getSession().beginTransaction();
        Staff st = dao.findById(11);
        Staff staff = new Staff();
        staff.setName("nguyen khac tu");
        staff.setEmail("tubcvt@gmail.com");
        staff.setAddress("phu do my dinh");
        dao.save(staff);
        dao.getSession().getTransaction().commit();
        System.out.println("done");
    }//GEN-LAST:event_jButton1MouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
