/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputStudent.java
 *
 * Created on Apr 3, 2011, 4:44:19 PM
 */
package aptech.view.student;

import api.StaffDAO;
import api.Student;
import api.StudentCourseRegistration;
import api.StudentCourseRegistrationDAO;
import api.StudentDAO;
import aptech.util.AppUtil;
import aptech.util.Constant;
import aptech.util.IsSure;
import aptech.util.ValidatePerson;
import aptech.util.ValidateUtil;
import aptech.view.control.ImageControl;
import aptech.view.control.TtsDateChooser;
import aptech.view.control.image.ImageFileChooser;

import java.io.IOException;
import java.net.URL;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import resources.images.PathUtil;

/**
 *
 * @author bo
 */
public class InputStudent extends javax.swing.JPanel {

    /** Creates new form InputStudent */
    public InputStudent() throws IOException {
        initComponents();
        initDefaultImage();
        initStudentToEdit();
        initDateChooser();
    }

    protected void initComponentV2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnImg = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStudentCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        cmbSex = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 300));

        pnImg.setPreferredSize(new java.awt.Dimension(200, 202));

        javax.swing.GroupLayout pnImgLayout = new javax.swing.GroupLayout(pnImg);
        pnImg.setLayout(pnImgLayout);
        pnImgLayout.setHorizontalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnImgLayout.setVerticalGroup(
            pnImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        jButton2.setText("Select Photo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Student Code");

        jLabel2.setText("Name");

        jLabel3.setText("Address");

        jLabel6.setText("Phone Number");

        jLabel7.setText("Email");

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fermale", "Male", " " }));

        jLabel8.setText("Sex");

        jLabel4.setText("Date Of Birth");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(204, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbSex, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void initStudentToEdit() {
        this.btnDelete.setVisible(false);
        return;
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ImageFileChooser fileChooser = new ImageFileChooser();
        int result = fileChooser.showDialog(this, "Select image");
        if (result == fileChooser.APPROVE_OPTION) {
            try {
                imgControl = new ImageControl(fileChooser.getSelectedFile().getAbsolutePath());

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, Constant.ERROR_STRING);
            }
        }
        this.pnImg.removeAll();
        this.pnImg.add(imgControl);
        this.validate();
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {

            // validate
            if (!isValidate()) {
                return;
            }
            // confirm before save
            if (!IsSure.confirm(confirmSaveMessage)) {
                return;
            }

            String errorMsg = initStudentFromUI();
            if (errorMsg.isEmpty()) {
                StudentDAO dao = new StudentDAO();
                dao.getSession().beginTransaction();
                dao.save(this.student);
                //dao.savePhoto(student);
                dao.getSession().getTransaction().commit();


            } else {
                AppUtil.showErrMsg(errorMsg);
            }


        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (student != null) {
            if (IsSure.confirm(this.confirmDeleteMessage)) {
                StudentDAO dao = new StudentDAO();
                dao.getSession().beginTransaction();
                dao.delete(student);
                studentCourseRegistrationDAO.deleteByStudent(student.getStudentId());
                dao.getSession().getTransaction().commit();
                AppUtil.showNoticeMessage(Constant.NOTICE_TO_DELETE_STUDENT);
                this.btnDelete.setEnabled(false);
                this.btnSave.setEnabled(false);
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void initDefaultImage() throws IOException {
        URL resource = PathUtil.class.getResource(Constant.DEFAULT_IMG_NAME);
        imgControl = new ImageControl(resource.getPath());
        this.pnImg.add(imgControl);

    }

    private void initDateChooser() {
        dateChooserCombo = new TtsDateChooser();
        dateChooserCombo.setSize(168, 18);
        this.jPanel1.add(dateChooserCombo);
    }

    protected void initDateChooser(Date startDate) {
        initDateChooser();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(startDate);
        this.dateChooserCombo.setSelectedDate(calendar);
    }

    // Get student info input form if validation fail a message will return
    protected String initStudentFromUI() throws ParseException {
        String errMsg = "";
        if (student == null) {
            this.student = new Student();
        }
        this.student.setAddress(this.txtAddress.getText().trim());
        this.student.setEmail(this.txtEmail.getText().trim());
        this.student.setName(this.txtName.getText().trim());
        this.student.setPhoneNumber(this.txtPhoneNumber.getText());
        this.student.setStudentCode(this.txtStudentCode.getText().trim());
        String cmbSexValue = this.cmbSex.getSelectedItem().toString();
        if (cmbSexValue.equalsIgnoreCase(Constant.MALE)) {
            this.student.setSex(true);
        } else {
            this.student.setSex(false);
        }
        this.student.setDateOfBirth(this.dateChooserCombo.getDate());

        if (imgControl.getImgData() != null) {
            student.setPhoto(imgControl.getImgData());
        }
        return errMsg;
    }
    // validate student from user input 

    private boolean isValidate() throws ParseException {
        String msg = null;
        // validate staff code
        String staffCode = this.txtStudentCode.getText().trim();
        if (staffCode.isEmpty()) {
            AppUtil.showErrMsg(Constant.STUDENT_CODE_INVALID);
            return false;
        }
        StudentDAO dao = new StudentDAO();
        List lstStudent = dao.findByStudentCode(staffCode);
        if (lstStudent.size() > 0) {
            if (student == null) {
                AppUtil.showErrMsg(Constant.STUDENT_CODE_IS_EXISTED);
                return false;
            }
        }

        if (this.txtName.getText().trim().isEmpty()) {
            AppUtil.showErrMsg(Constant.NAME_INVALID);
            return false;
        }

        if (this.txtAddress.getText().trim().isEmpty()) {
            AppUtil.showErrMsg(Constant.ADDRESS_INVALID);
            return false;
        }

        msg = ValidatePerson.chekDOB(dateChooserCombo.getDate());
        if (msg != null) {
            AppUtil.showErrMsg(msg);
            return false;
        }

        msg = ValidatePerson.isPhoneNumber(txtPhoneNumber.getText());
        if (msg != null) {
            AppUtil.showErrMsg(msg);
            return false;
        }
        msg = ValidatePerson.isEmail(this.txtEmail.getText().trim());
        if (msg != null) {
            AppUtil.showErrMsg(msg);
            return false;
        }
        return true;
    }

    protected void initStudentFromModel(Student studentFromModel) {
        try {
            this.student = studentFromModel;
            this.txtAddress.setText(student.getAddress());
            this.txtEmail.setText(student.getEmail());
            this.txtName.setText(student.getName());
            this.txtPhoneNumber.setText(student.getPhoneNumber());
            this.txtStudentCode.setText(student.getStudentCode());
            this.txtStudentCode.setEditable(false);
            initDateChooser(student.getDateOfBirth());
            this.imgControl = new ImageControl(student.getPhoto());
            this.pnImg.add(imgControl);
            if (student.getSex()) {
                this.cmbSex.setSelectedIndex(1);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, Constant.ERROR_STRING);
        }
    }
    String confirmSaveMessage = Constant.SURE_TO_SAVE_STUDENT;
    String confirmDeleteMessage = Constant.SURE_TO_DELETE_STUDENT;
    TtsDateChooser dateChooserCombo;
    protected Student student;
    private ImageControl imgControl;
    private StudentCourseRegistration studentCourseRegistration=new StudentCourseRegistration();
    private  StudentCourseRegistrationDAO studentCourseRegistrationDAO= new StudentCourseRegistrationDAO();

    public JButton getBtnDelete() {
        return btnDelete;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnImg;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtStudentCode;
    // End of variables declaration//GEN-END:variables
}
