/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SchedulePanel.java
 *
 * Created on Apr 13, 2011, 7:04:53 PM
 */
package aptech.view.control;

import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author bo
 */
public class SchedulePanel extends javax.swing.JPanel {

    private List<ClassStartTime> lstStartTime = new ArrayList<ClassStartTime>();
    /** Creates new form SchedulePanel */
    Integer hourPerlession = 0;

    public SchedulePanel() {
        initPanelInput();
        initDateFormat();
        init();
    }

    public Integer getHourPerlession() {
        return hourPerlession;
    }

    public void setMinutePerLession(Integer minute) {
        this.hourPerlession = minute;
        for (ClassStartTime cst : lstStartTime) {
            cst.setMinuteConstraint(minute);
            cst.resetTime();

        }
    }

    public List<TtsDateModel> getDateModel() {
        List<TtsDateModel> lstDate = new ArrayList<TtsDateModel>();
        for (ClassStartTime cst : lstStartTime) {
            if (cst.getDate() != null) {
                lstDate.add(cst.getDateModel());
            }
        }
        return lstDate;
    }

    public void init() {

        ClassStartTime tMon = new ClassStartTime("Monday", this.hourPerlession);
        tMon.setDayOfWeek(Calendar.MONDAY);
        ClassStartTime tTue = new ClassStartTime("Tuesday", this.hourPerlession);
        tTue.setDayOfWeek(Calendar.TUESDAY);
        ClassStartTime tWed = new ClassStartTime("Wednesday", this.hourPerlession);
        tWed.setDayOfWeek(Calendar.WEDNESDAY);
        ClassStartTime tThur = new ClassStartTime("Thursday", this.hourPerlession);
        tThur.setDayOfWeek(Calendar.THURSDAY);
        ClassStartTime tFri = new ClassStartTime("Friday", this.hourPerlession);
        tFri.setDayOfWeek(Calendar.FRIDAY);
        ClassStartTime tSat = new ClassStartTime("Saturday", this.hourPerlession);
        tSat.setDayOfWeek(Calendar.SATURDAY);
        ClassStartTime tSun = new ClassStartTime("Sunday", this.hourPerlession);
        tSun.setDayOfWeek(Calendar.SUNDAY);

        lstStartTime.add(tMon);
        lstStartTime.add(tTue);
        lstStartTime.add(tWed);
        lstStartTime.add(tThur);
        lstStartTime.add(tFri);
        lstStartTime.add(tSat);
        lstStartTime.add(tSun);
        jPanel1.add(tMon);
        jPanel1.add(tTue);
        jPanel1.add(tWed);
        jPanel1.add(tThur);
        jPanel1.add(tFri);
        jPanel1.add(tSat);
        jPanel1.add(tSun);
    }

    public void initDateFormat() {

        jPanel1.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 8));


    }

    public void initPanelInput() {
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel2.setLayout(new FlowLayout());
        JLabel lbClass = new JLabel("Select Class");
        JComboBox cmbClass = new JComboBox(new String[]{"C0905l", "C0906l"});
        jPanel2.add(lbClass);
        jPanel2.add(cmbClass);


        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(300, 381));
        setLayout(new FlowLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(250, 250));
        //add(jPanel2, java.awt.BorderLayout.WEST);
        //add(jPanel2);
        //ClassScheduleMain csm=new ClassScheduleMain();
        //add(csm);
        add(jPanel1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Schedule", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 381));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(136, 250));
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JPanel jPanel2;
}
