/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InputSubject.java
 *
 * Created on Apr 10, 2011, 6:23:53 PM
 */

package aptech.view.semester;

import api.SubjectDAO;
import aptech.util.ValidateUtil;
import api.Subject;
import javax.swing.JOptionPane;
/**
 *
 * @author anhson
 */
public class InputSubject extends javax.swing.JPanel {

    /** Creates new form InputSubject */
    public InputSubject() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        txtSubCode = new javax.swing.JTextField();
        txtSubName = new javax.swing.JTextField();
        lblDesc = new javax.swing.JLabel();
        lblCourceName1 = new javax.swing.JLabel();
        lblCourceName = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        btnAdd.setText("Add new");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblDesc.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDesc.setText("Description :");

        lblCourceName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCourceName1.setText("Subject code :");

        lblCourceName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCourceName.setText("Subject Name :");

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Subject Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCourceName)
                                    .addComponent(lblDesc)
                                    .addComponent(lblCourceName1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSubCode, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSubName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(btnAdd))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCourceName1)
                            .addComponent(txtSubCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSubName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCourceName)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesc)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        ValidateUtil validate = new ValidateUtil();
        if(!validate.isEmpty(txtSubName.getText())) {
            txtSubName.requestFocus();
        } else if(!validate.isEmpty(txtSubCode.getText())) {
            txtSubCode.requestFocus();
        }else if(!validate.isEmpty(txtDescription.getText())) {
            txtDescription.requestFocus();
        }else {
            try{
                SubjectDAO subDAO = new SubjectDAO();
                Subject subject = new Subject();
                String subName = txtSubName.getText();
                String subCOde= txtSubCode.getText();
                String subDesc = txtDescription.getText();

                if(subDAO.findBySubjectCode(subCOde).size()>0) {
                    JOptionPane.showMessageDialog(null,"Code early exits database !","System saying",JOptionPane.WARNING_MESSAGE);
                    txtSubCode.requestFocus();
                }else{
                    subDAO.getSession().beginTransaction();
                    subject.setSubjectName(subName);
                    subject.setSubjectCode(subCOde);
                    subject.setDescription(subDesc);
                    subDAO.save(subject);
                    subDAO.getSession().getTransaction().commit();
                    JOptionPane.showMessageDialog(null,"Insert data succesffuly");
                }
            }catch(Exception ex) {
                JOptionPane.showMessageDialog(null,"Error !","System saying",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
}//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCourceName;
    private javax.swing.JLabel lblCourceName1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtSubCode;
    private javax.swing.JTextField txtSubName;
    // End of variables declaration//GEN-END:variables

}
