/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResulPanel.java
 *
 * Created on 10-04-2011, 14:39:29
 */
package aptech.view.staff;

import api.Staff;
import api.StaffDAO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thinp
 */
public class ResulPanel extends javax.swing.JPanel {

    /** Creates new form ResulPanel */
    public ResulPanel() {
        initComponents();
        creatTable();
        creatTable(modelTable);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void creatTable() {

        listStaff = (List<Staff>) staffDAO.findAll();
        String columName[] = {"Name", "Email"};
        modelTable = new DefaultTableModel(columName, 1);
        for (Staff staff : listStaff) {
            vectorString = new Vector<String>();
            vectorString.add(staff.getName());
            modelTable.addRow(vectorString);
        }
    }

    public void creatTable(DefaultTableModel model) {
        model = modelTable;
        tableResul = new JTable();
        tableResul.setModel(model);
        scroll = new JScrollPane(tableResul);
        scroll.add(tableResul);
        scroll = new JScrollPane(tableResul);
        frame.add(scroll);
        frame.setVisible(true);
        this.add(tableResul);
        this.validate();
        this.repaint();
        frame.setSize(200, 200);
        frame.setVisible(false);
    }
    private List<Staff> listStaff;
    private Vector<String> vectorString;
    private DefaultTableModel modelTable;
    private JTable tableResul;
    JFrame frame = new JFrame();
    JScrollPane scroll;
    StaffDAO staffDAO = new StaffDAO();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
