/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResulPanel.java
 *
 * Created on 10-04-2011, 14:39:29
 */
package aptech.view.staff;

import api.ClassOffer;
import api.ClassOfferDAO;
import api.SubjectAssignment;
import api.SubjectAssignmentDAO;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 *
 * @author thinp
 */
public class ResulPanel extends javax.swing.JPanel {

    /** Creates new form ResulPanel */
    public ResulPanel() {
        initComponents();
        initClass();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cnxClassName = new javax.swing.JComboBox();

        jLabel1.setText("Class Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cnxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void initClass() {
        int a = 71;
        List<SubjectAssignment> test = subjectAssignmentDAO.findByStaffId(a);
        HashSet<Integer> lstIDClass = new HashSet<Integer>();

        for (SubjectAssignment subjectTemp : test) {
            lstIDClass.add(subjectTemp.getClassOfferId());
        }
        System.out.println(lstIDClass);
        for (Integer integer : lstIDClass) {
            //ClassOffer classTemp = new ClassOffer();
            System.out.println(classOfferDAO.findById(integer).getClassCode());
        }
    }
    private ClassOffer classOffer = new ClassOffer();
    private ClassOfferDAO classOfferDAO = new ClassOfferDAO();
    private SubjectAssignment assignment = new SubjectAssignment();
    private SubjectAssignmentDAO subjectAssignmentDAO = new SubjectAssignmentDAO();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cnxClassName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
