/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainTimeForm.java
 *
 * Created on Apr 25, 2011, 4:07:38 PM
 */

package aptech.view.timeline;

import java.awt.FlowLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author bo
 */
public class MainTimeForm extends javax.swing.JPanel {

    /** Creates new form MainTimeForm */
    public MainTimeForm() {
        initComponents();
        init();
    }

    private void init()
    {
        setLayout(new FlowLayout(FlowLayout.CENTER));
        prMain=new MainTimeTable();
        mainPn=new JScrollPane(prMain);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
    private JScrollPane mainPn;
    private JLabel lbTitle;
    private JPanel pnButtons;
    private JButton btnPre;
    private JButton btnNext;
    private MainTimeTable prMain;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
