/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllStudent.java
 *
 * Created on 22-04-2011, 10:26:17
 */

package aptech.view.semester;

import api.StudentDAO;
import api.StudentV2;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author thinp
 */
public class AllStudent extends javax.swing.JFrame {

    /** Creates new form AllStudent */
    public AllStudent(List<StudentV2> lstStudent) {
        initComponents();
        initTable(lstStudent);
        this.repaint();
        this.validate();
    }
     private void initTable(List<StudentV2> lstStudent) {
        JTable jTable = new JTable();
        StudentDAO dao = new StudentDAO();
        aptech.view.staff.StudentTableModel model = new aptech.view.staff.StudentTableModel(lstStudent);
        jTable.setModel(model);
         JScrollPane pane = new JScrollPane(jTable);
        pane.setPreferredSize(new Dimension(300, 300));
        this.getContentPane().setLayout(new BorderLayout());
        this.getContentPane().add(pane,BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AllStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
