/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassSchedule.java
 *
 * Created on Apr 13, 2011, 6:22:55 PM
 */
package aptech.view.staff;

import aptech.view.control.ClassScheduleMain;
import aptech.view.control.SchedulePanel;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author bo
 */
public class ClassSchedule extends javax.swing.JPanel {

    /** Creates new form ClassSchedule */
    public ClassSchedule() {
        initComponents();
    }
    public ClassSchedule(int staffId) {
        initComponents();
        SchedulePanel schedulePanel = new SchedulePanel();
        ClassScheduleMain csm=new ClassScheduleMain(staffId);
        csm.setSchedulePanel(schedulePanel);
        this.pnMain.setLayout(new BorderLayout());
        this.pnMain.add(csm,BorderLayout.CENTER);
        this.pnSec.setLayout(new BorderLayout());
        this.pnSec.add(schedulePanel,BorderLayout.CENTER);

        this.revalidate();
        this.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        pnSec = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(500, 500));

        pnMain.setPreferredSize(new java.awt.Dimension(350, 370));

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnSecLayout = new javax.swing.GroupLayout(pnSec);
        pnSec.setLayout(pnSecLayout);
        pnSecLayout.setHorizontalGroup(
            pnSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );
        pnSecLayout.setVerticalGroup(
            pnSecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(pnSec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSec;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
//        JFrame jf = new JFrame();
//        long staffId=10;
////        ClassSchedule cs = new ClassSchedule(staffId);
//        jf.getContentPane().setLayout(new BorderLayout());
//        jf.getContentPane().add(cs,BorderLayout.CENTER);
//        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        jf.pack();
//        jf.setVisible(true);

    }
}
