/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ResulPanel.java
 *
 * Created on 10-04-2011, 14:39:29
 */
package aptech.view.staff;

import api.AssigmentSchedule;
import api.AssigmentScheduleDAO;
import api.Attendance;
import api.AttendanceDAO;
import api.ClassOffer;
import api.ClassOfferDAO;
import api.CommonDAO;
import api.Student;
import api.StudentCourseRegistration;
import api.StudentCourseRegistrationDAO;
import api.StudentDAO;
import api.StudentV2;
import api.Subject;
import api.SubjectAssignment;
import api.SubjectAssignmentDAO;
import api.SubjectDAO;
import aptech.util.IsSure;
import aptech.view.control.CmbObject;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.TimeZone;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import sun.misc.Cleaner;

/**
 *
 * @author thinp
 */
public class ResulPanel extends javax.swing.JPanel {

    /** Creates new form ResulPanel */
    public ResulPanel() {
        initComponents();
        initClass();
        //initSubject();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbxClassName = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbxStudent = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbxSubject = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        bttSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbxDate = new javax.swing.JComboBox();

        jLabel1.setText("Class Name");

        cbxClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClassNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Student Code");

        cbxStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStudentActionPerformed(evt);
            }
        });

        jLabel3.setText("Subject");

        cbxSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSubjectActionPerformed(evt);
            }
        });

        jLabel4.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        bttSave.setText("Save");
        bttSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSaveActionPerformed(evt);
            }
        });

        jLabel5.setText("Status");

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "P", "A" }));

        jLabel6.setText("Date");

        cbxDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SelectDate" }));
        cbxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxDate, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxClassName, javax.swing.GroupLayout.Alignment.LEADING, 0, 103, Short.MAX_VALUE)
                            .addComponent(cbxStudent, javax.swing.GroupLayout.Alignment.LEADING, 0, 103, Short.MAX_VALUE)
                            .addComponent(bttSave, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSubject, javax.swing.GroupLayout.Alignment.LEADING, 0, 103, Short.MAX_VALUE))
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(bttSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClassNameActionPerformed
        // TODO add your handling code here:
        try {
            int clsOfferID = lstIDClass.get(cbxClassName.getSelectedIndex());
            List<StudentCourseRegistration> lstReg = new ArrayList<StudentCourseRegistration>();
            lstReg = studentCourseRegistrationDAO.findByClassOfferId(clsOfferID);
            lstStudentID.clear();
            if (cbxStudent.getItemCount() > 0) {
                cbxStudent.removeAllItems();
            }
            for (StudentCourseRegistration stuIdTemp : lstReg) {
                lstStudentID.add(stuIdTemp.getStudentId());
            }
            for (Integer integer : lstStudentID) {
                studentV2 = studentDAO.findByIdV2(integer);
                cbxStudent.addItem(studentV2.getStudentCode() + "_" + studentV2.getName());
            }
            initSubject();
        } catch (Exception e) {
            return;
        }
    }//GEN-LAST:event_cbxClassNameActionPerformed

    private void bttSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSaveActionPerformed

        // TODO add your handling code here:

        int assCheIDTemp = lstAssigmentSchedules.get(cbxDate.getSelectedIndex()).getAssigmentScheduleId();
        deString = txtDescription.getText();
        int temp = cbxStatus.getSelectedIndex();
        if (temp == 0) {
            statusAttendance = 0;
        }
        if (temp == 1) {
            statusAttendance = 1;
        }
        if(deString.isEmpty()){
        JOptionPane.showMessageDialog(this, "Description is not null", "Eros", JOptionPane.WARNING_MESSAGE);}
        else{
        attendance.setAbsenceStatus(statusAttendance);
        attendance.setAssigmentScheduleId(assCheIDTemp);
        attendance.setDescription(deString);
        attendance.setStudentId(studentIDTemp);
        attendanceDAO.getSession().beginTransaction();
        attendanceDAO.save(attendance);
        attendanceDAO.getSession().getTransaction().commit();
        JOptionPane.showMessageDialog(this, "Add Ok");
        this.bttSave.setEnabled(false);
        }
        
        


        

    }//GEN-LAST:event_bttSaveActionPerformed

    private void cbxStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStudentActionPerformed
        // TODO add your handling code here:
        studentIDTemp = lstStudentID.get(cbxStudent.getSelectedIndex());
    }//GEN-LAST:event_cbxStudentActionPerformed

    private void cbxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDateActionPerformed

    private void cbxSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSubjectActionPerformed
        initSchedule();
        // TODO add your handling code here:
}//GEN-LAST:event_cbxSubjectActionPerformed

    public void initSubject() {
        int id = lstIDClass.get(cbxClassName.getSelectedIndex());
        List<SubjectAssignment> lstTemp = subjectAssignmentDAO.findByClassAndStaff(id, a);
        if (hsSubjects.size() > 0) {
            hsSubjects.clear();
        }
        for (SubjectAssignment subjectAssignment : lstTemp) {
            int idSubjectTemp = subjectAssignment.getSubjectId();
            subject = subjectDAO.findById(idSubjectTemp);
            hsSubjects.add(subject);
            idSubject.add(idSubjectTemp);
        }
        if (cbxSubject.getItemCount() > 0) {
            cbxSubject.removeAllItems();
        }
        for (Subject subTemp : hsSubjects) {
            cbxSubject.addItem(subTemp.getSubjectName());
        }
    }

    void initClass() {
        hsIDClass = new HashSet<Integer>();

        for (SubjectAssignment subjectTemp : test) {
            hsIDClass.add(subjectTemp.getClassOfferId());
        }
        for (Integer integer : hsIDClass) {

            cbxClassName.addItem(classOfferDAO.findById(integer).getClassCode());
            lstIDClass.add(integer);
        }



    }

    void initSchedule() {
        int classID = lstIDClass.get(cbxClassName.getSelectedIndex());
        int subjectID = idSubject.get(cbxSubject.getSelectedIndex());
        List<SubjectAssignment> lstList = subjectAssignmentDAO.findByClassStaffAndSubject(classID, a, subjectID);
        int classOfferID = lstList.get(0).getClassOfferDetailId();
        lstAssigmentSchedules = assigmentScheduleDAO.findByClassOfferDetailId(classOfferID);
        SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE/MM/dd/yyyy");
        if (cbxDate.getItemCount() > 0) {
            cbxDate.removeAllItems();
        }
        for (AssigmentSchedule assSchedule : lstAssigmentSchedules) {
            String temp = dateFormat.format(assSchedule.getDate());
            cbxDate.addItem(temp);
        }

    }
    private ClassOffer classOffer = new ClassOffer();
    private ClassOfferDAO classOfferDAO = new ClassOfferDAO();
    private SubjectAssignment assignment = new SubjectAssignment();
    private SubjectAssignmentDAO subjectAssignmentDAO = new SubjectAssignmentDAO();
    private StudentV2 studentV2 = new StudentV2();
    private StudentDAO studentDAO = new StudentDAO();
    private StudentCourseRegistration studentCourseRegistration = new StudentCourseRegistration();
    private StudentCourseRegistrationDAO studentCourseRegistrationDAO = new StudentCourseRegistrationDAO();
    int a = 74;
    private Subject subject = new Subject();
    private SubjectDAO subjectDAO = new SubjectDAO();
    private HashSet<Integer> hsIDClass;
    private List<SubjectAssignment> test = subjectAssignmentDAO.findByStaffId(a);
    private List<Integer> lstIDClass = new ArrayList<Integer>();
    private List<Student> lstStudent = new ArrayList<Student>();
    private List<Integer> lstClassOfferDetail = new ArrayList<Integer>();
    private List<AssigmentSchedule> lstAssigmentSchedules = new ArrayList<AssigmentSchedule>();
    private AssigmentScheduleDAO assigmentScheduleDAO = new AssigmentScheduleDAO();
    private List<Integer> lstStudentID = new ArrayList<Integer>();
    private HashSet<Subject> hsSubjects = new HashSet<Subject>();
    private List<Integer> idSubject = new ArrayList<Integer>();
    private int studentIDTemp;
    private int scheduleId;
    private String deString;
    private Short statusAttendance;
    private Attendance attendance = new Attendance();
    private AttendanceDAO attendanceDAO = new AttendanceDAO();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttSave;
    private javax.swing.JComboBox cbxClassName;
    private javax.swing.JComboBox cbxDate;
    private javax.swing.JComboBox cbxStatus;
    private javax.swing.JComboBox cbxStudent;
    private javax.swing.JComboBox cbxSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
